// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SorterExpress.Data.DbContext;

#nullable disable

namespace SorterExpress.Data.Migrations
{
    [DbContext(typeof(SorterExpressDbContext))]
    partial class SorterExpressDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("SorterExpress.Data.Model.FileData", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("AutoClassificationWeights")
                        .HasColumnType("TEXT");

                    b.HasKey("Path");

                    b.ToTable("FileData");
                });
#pragma warning restore 612, 618
        }
    }
}
