//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SorterExpress.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MoveSortedFiles {
            get {
                return ((bool)(this["MoveSortedFiles"]));
            }
            set {
                this["MoveSortedFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int TagSearchStart {
            get {
                return ((int)(this["TagSearchStart"]));
            }
            set {
                this["TagSearchStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoResetTagSearchBox {
            get {
                return ((bool)(this["AutoResetTagSearchBox"]));
            }
            set {
                this["AutoResetTagSearchBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayAllTags {
            get {
                return ((bool)(this["DisplayAllTags"]));
            }
            set {
                this["DisplayAllTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> Tags {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["Tags"]));
            }
            set {
                this["Tags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastUsedDirectory {
            get {
                return ((string)(this["LastUsedDirectory"]));
            }
            set {
                this["LastUsedDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VlcLocation {
            get {
                return ((string)(this["VlcLocation"]));
            }
            set {
                this["VlcLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VideoVolume {
            get {
                return ((int)(this["VideoVolume"]));
            }
            set {
                this["VideoVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VideoMute {
            get {
                return ((bool)(this["VideoMute"]));
            }
            set {
                this["VideoMute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> SubfolderNames {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["SubfolderNames"]));
            }
            set {
                this["SubfolderNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> SubfolderDirectories {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["SubfolderDirectories"]));
            }
            set {
                this["SubfolderDirectories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DuplicatesSearchImages {
            get {
                return ((bool)(this["DuplicatesSearchImages"]));
            }
            set {
                this["DuplicatesSearchImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DuplicatesSearchVideos {
            get {
                return ((bool)(this["DuplicatesSearchVideos"]));
            }
            set {
                this["DuplicatesSearchVideos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int DuplicatesSearchSimilarityPercentage {
            get {
                return ((int)(this["DuplicatesSearchSimilarityPercentage"]));
            }
            set {
                this["DuplicatesSearchSimilarityPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DuplicatesSearchThreadCount {
            get {
                return ((int)(this["DuplicatesSearchThreadCount"]));
            }
            set {
                this["DuplicatesSearchThreadCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FastResizing {
            get {
                return ((bool)(this["FastResizing"]));
            }
            set {
                this["FastResizing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DuplicatesMergeFileTags {
            get {
                return ((bool)(this["DuplicatesMergeFileTags"]));
            }
            set {
                this["DuplicatesMergeFileTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DuplicatesOnlyKeepTagsInLibrary {
            get {
                return ((bool)(this["DuplicatesOnlyKeepTagsInLibrary"]));
            }
            set {
                this["DuplicatesOnlyKeepTagsInLibrary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DuplicatesCropLeftRightSides {
            get {
                return ((bool)(this["DuplicatesCropLeftRightSides"]));
            }
            set {
                this["DuplicatesCropLeftRightSides"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DuplicatesCropTopBottomSides {
            get {
                return ((bool)(this["DuplicatesCropTopBottomSides"]));
            }
            set {
                this["DuplicatesCropTopBottomSides"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoResetSubfolderSearchBox {
            get {
                return ((bool)(this["AutoResetSubfolderSearchBox"]));
            }
            set {
                this["AutoResetSubfolderSearchBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DuplicatesOnlyMatchSameFileTypes {
            get {
                return ((bool)(this["DuplicatesOnlyMatchSameFileTypes"]));
            }
            set {
                this["DuplicatesOnlyMatchSameFileTypes"] = value;
            }
        }
    }
}
